### ISSUE TITLE
seastar tcpserver - goclient txtx test on DPDK  is underperfoming x2 

### ISSUE THREAD

**Issue by slivne** [cloudius-systems/seastar#12]
http://jenkins.cloudius-systems.com:8080/job/seastar-private-tcpserver-perf/8/PerfPublisher/

increasing the size of user_queue_space x2 does not help (user_queue_space = {212992 * 2}) - the associated results are from a build using asias/txtx branch in seastar-dev that has this change.

On Thor-Loki:

Goserver | tcp-server stack-native-dpdk171 | tcpserver stack-native-dpdk18 | tcpserver stack-posix
------------ | ------------- | ------------ | -------------
8.915581406 | 17.087416845  | 17.867953145  | 8.914382154 

values are seconds to complete the tests - lower is better

To reproduce you can tun the tests in the following manner:
  * install + configure dpdk
  * start tcpserver
  * clone tests.git
  * cd tests
  * scripts/tester.py  run  --config_param sut.ip:<ip> --config_param tester.ip:x apps/tcp/tests/test_1_goclient/tester
  * check the output at apps/tcp/tests/test_1_goclient/tester/out

or 
  * install + configure dpdk
  * start tcpserver 
  * clone tests.git
  * cd tests/apps/tcp/tests/test_1_goclient/tester
  * go run client.go -h <ip>

Please note you can use client.go -conn 1 option to limit the number of connections

**Comment by slivne** [comment]
@asias the latest results from the nightly perf tests indicate that we have closed the gap 
can you have a look

http://jenkins.cloudius-systems.com:8080/job/seastar-tcpserver-perf/38/

if all is ok can we close this issue ?

**Comment by asias** [comment]
@slivne let's close this issue. TSO support (193416054902915a1a99916e2243682d0c4326ae) in dpdk is supposed to close the x2 gap.
